#!/bin/sh
# postinst script for #PACKAGE#
#
# see: dh_installdeb(1)

set -e

case "$1" in
    install)
        if [ ! $(id -u slurm 2> /dev/null) ]; then
            useradd --system --no-create-home --uid #UID# --user-group --home-dir /nonexistent --shell /usr/sbin/nologin slurm
        fi
    ;;

    upgrade|abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
