#!/bin/sh
# postinst script for #PACKAGE#
#
# see: dh_installdeb(1)

set -e

case "$1" in
    configure)
        chown slurm:slurm /var/lib/slurm
        chown slurm:slurm /var/lib/slurm/slurmctld
        chown slurm:slurm /var/log/slurm
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
